### PR TITLE
LPS-105136 Adds missing Column Spacing selector on Spacing configuration panel

### PR DESCRIPTION
**Pull request by diegonvs**
Hey Julien, I didn't implemented the Number of Columns behaviour because it demand more work on it. Should I create another ticket for working on this? However all values of the Spacing Configuration Panel are being passed via redux as properties to Container component 

@julien 
@matuzalemsteles
@p2kmgcl

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
280a2bd is weird 🤔

**Comment by julien** [comment]
> [280a2bd](https://github.com/julien/liferay-portal/commit/280a2bdf583eebb01cf2048b0e8e1a75dfa08ada) is weird

That's probably because you should rebase with master before sending.

**Comment by julien** [comment]
@diegonvs could you please rebase with `master` and resend?

**Comment by diegonvs** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/81818

**Pull request closed without merging**
