### PR TITLE
LPS-86044 Don't show two error messages

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi @julien ,

Can you review this PR, please?

You can find further information in [LPS-86044](https://issues.liferay.com/browse/LPS-86044) and [this comment](https://issues.liferay.com/browse/PTR-438?focusedCommentId=1595453&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1595453) in PTR-438.

Thanks,

/cc @NemethNorbert

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by julien** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by julien** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/64454. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
