### PR TITLE
LPS-107374 Extract all IE-specific CSS to its own module

### PR DESCRIPTION
**Pull request by julien**
Hi @john-co,

I was wondering if you could help me review these changes when/if you have a moment.

I originally sent the PR to @brianchandotcom over here https://github.com/brianchandotcom/liferay-portal/pull/85338 but there were lots of  CI errors: I had a look at them, but they don't seem related to these changes.

Thanks!

### CODE REVIEW

**Comment by julien** [comment]
ci:test:bundle

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Hi @julien, 

Testing manually, when navigating to a newly created page, there's a warning error thrown: 
- `2020-02-27 19:06:50.973 WARN  [http-nio-8080-exec-2][code_jsp:173] {code="404", msg="Not Found", uri=/o/site-navigation-menu-web/css/main.css}
`
image

That looks like the same issue the automation tests are complaining about.

**Comment by julien** [comment]
@john-co thanks, and I agree that's the same issue.
@marcoscv-work does this error ring a bell? seems we deleted this file but not the references to it.

**Comment by john-co** [comment]
disabling minifier and other fast load properties throws these errors:
image

**Comment by julien** [comment]
@john-co thanks again for the help!
submitted to https://github.com/marcoscv-work/liferay-portal/pull/305

**Pull request closed without merging**
