### PR TITLE
LPS-107374 - Remove css reference

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by julien** [comment]
ci:test:bundle

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
ci:test:stable

**Comment by julien** [comment]
@john-co this last error doesn't seem related to our change,
could you confirm when you have some time? 

Thanks in advance

**Comment by john-co** [comment]
ci:stable

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Hi @julien, agreed the ci stable failures look unrelated.
- modules-unit-jdk8 - known failure observed in upstream
- PortalSmokeUpgrade#ViewPortalSmokeArchive621021 - seems like a fluke

`ci test relevant` [results comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1027175527&testrayRunIdA=1027176873&statusB=2) - looks like a fluke where the page got hung up.

Rerunning the tests to be doubly sure but I'm 90% sure that these test failures are unrelated.

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark:

**Pull request closed without merging**
