### PR TITLE
IFI-1450 Upgrade react-dnd to v10.0.1

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test:bundle

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
ci:test:norebase:bundle

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
ci test is not working because of a poshi-subrepo change in upstream https://github.com/brianchandotcom/liferay-portal/pull/84723

same errors are seen in https://github.com/brianchandotcom/liferay-portal/pull/84867

This should be resolved when BChan's origin is synced

**Comment by john-co** [comment]
try testing with rebased BChan origin:  https://github.com/john-co/liferay-portal/pull/245

**Comment by john-co** [comment]
Looks like `IFI` is not being accepted in the commit messages for portal repo, see https://github.com/brianchandotcom/liferay-portal/pull/84866#issuecomment-587734643

We can either create an LPS to make commits under or include `IFI` as part of the accepted commit starting text.

cc/ @julien @wincent

**Comment by wincent** [comment]
> Looks like `IFI` is not being accepted in the commit messages for portal repo

@john-co: Yeah, that's expected. Whenever we make a change in liferay-portal in service of an IFI, we have to create a LPS for the purposes of actually sending to Brian. On a couple of other occasions I have asked @jbalsas about whether we could change the rules in order to minimize this kind of overhead (ie. by adding IFI to the list of allowed prefixes, or by starting to organize frontend work under the LPS project), but it is something that he and Esther need to weigh up as it would have a lot of impact on how they do project management.

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
Hi @julien, can you rebase your changes?

**Comment by julien** [comment]
@john-co of course, on top of liferay-portal/master right?

**Comment by john-co** [comment]
@julien, yes please

**Comment by julien** [comment]
@john-co should be rebased, thanks!

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
App Builder test failures look related:

- When navigating to Product Menu > Control Panel > App Builder > Custom Objects, the page doesn't load and there is a js error thrown:

image

Other test failures are not related
**Comparison details:**
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1012870736&testrayRunIdA=1012649191&statusB=2

**Comment by john-co** [comment]
js-unit test failed:

```
     [exec] > Task :apps:app-builder:app-builder-web:packageRunTest
     [exec] FAIL test/js/components/permissions/PermissionsModal.es.js
     [exec]   ??? Test suite failed to run
     [exec] 
     [exec]     TypeError: (0 , _reactDnd.DragDropContext) is not a function
     [exec] 
     [exec]       16 | import HTML5Backend from 'react-dnd-html5-backend';
     [exec]       17 | 
     [exec]     > 18 | export default DragDropContext(HTML5Backend);
     [exec]          |                ^
     [exec]       19 | 
     [exec] 
     [exec]       at Object.<anonymous> (../../data-engine/data-engine-taglib/src/main/resources/META-INF/resources/data_layout_builder/js/drag-and-drop/withDragAndDropContext.es.js:18:16)
     [exec]       at Object.<anonymous> (../../data-engine/data-engine-taglib/src/main/resources/META-INF/resources/data_layout_builder/js/App.es.js:24:1)
     [exec]       at Object.<anonymous> (../../data-engine/data-engine-taglib/src/main/resources/META-INF/resources/data_layout_builder/js/index.es.js:15:1)
     [exec]       at Object.<anonymous> (src/main/resources/META-INF/resources/js/components/permissions/PermissionsModal.es.js:18:1)
     [exec]       at Object.<anonymous> (test/js/components/permissions/PermissionsModal.es.js:18:1)
     [exec] 
     [exec] FAIL test/js/components/list-view/ListView.es.js
     [exec]   ??? Test suite failed to run
     [exec] 
     [exec]     TypeError: (0 , _reactDnd.DragDropContext) is not a function
     [exec] 
     [exec]       16 | import HTML5Backend from 'react-dnd-html5-backend';
     [exec]       17 | 
     [exec]     > 18 | export default DragDropContext(HTML5Backend);
     [exec]          |                ^
     [exec]       19 | 
     [exec] 
     [exec]       at Object.<anonymous> (../../data-engine/data-engine-taglib/src/main/resources/META-INF/resources/data_layout_builder/js/drag-and-drop/withDragAndDropContext.es.js:18:16)
     [exec]       at Object.<anonymous> (../../data-engine/data-engine-taglib/src/main/resources/META-INF/resources/data_layout_builder/js/App.es.js:24:1)
     [exec]       at Object.<anonymous> (../../data-engine/data-engine-taglib/src/main/resources/META-INF/resources/data_layout_builder/js/index.es.js:15:1)
     [exec]       at Object.<anonymous> (src/main/resources/META-INF/resources/js/components/management-toolbar/search/SearchBar.es.js:15:1)
     [exec]       at Object.<anonymous> (src/main/resources/META-INF/resources/js/components/management-toolbar/index.es.js:16:1)
     [exec]       at Object.<anonymous> (src/main/resources/META-INF/resources/js/components/list-view/ListView.es.js:21:1)
     [exec]       at Object.<anonymous> (test/js/components/list-view/ListView.es.js:20:1)
     [exec] 
     [exec] Test Suites: 2 failed, 4 passed, 6 total
     [exec] Tests:       17 passed, 17 total
     [exec] Snapshots:   0 total
     [exec] Time:        24.585s
     [exec] Ran all test suites.
     [exec] Command /opt/dev/projects/github/liferay-portal/modules/node_modules/liferay-npm-scripts/node_modules/.bin/jest --config TEMP_jest.config.json exited with code 1
     [exec] error Command failed with exit code 1.
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] 
     [exec] > Task :apps:app-builder:app-builder-web:packageRunTest FAILED
```

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by julien** [comment]
@john-co I'll work on updating those usages

**Comment by julien** [comment]
@john-co I review and fixed those errors - thanks again for the help.
Could you do a second round of testing when you have the chance?

**Comment by wincent** [comment]
@julien: may as well create an LPS at this point and rewrite those commit messages.

**Comment by julien** [comment]
@wincent yes that make sense.

@john-co if you'd rather test https://github.com/julien/liferay-portal/pull/228, since it is now an LPS if everything works we could send one.

Thanks!

**Comment by julien** [comment]
Closing this one since we've move to #228

**Pull request closed without merging**
