### PR TITLE
LPS-XXXXX Test local dependencies

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
Hi @julien,

TLDR All test failure results reported are not related to this pull.

All functional test failures are not related to this pull.

I looked at most of the integration and unit failures, and they are not related to this pull when comparing with an approximate upstream acceptance test run: https://test-1-1.liferay.com//userContent/jobs/test-portal-acceptance-upstream%28master%29/builds/6325/jenkins-report.html

The tests in /modules-semantic-versioning-jdk8 passes but one axis node was tripped red for some reason, causing the batch to think it failed.

:tada::tada:

**Comment by julien** [comment]
Hey @john-co ,

Thanks a lot for your time and the detailed information, much appreciated!
🎉

**Pull request closed without merging**
