### PR TITLE
[TECHNICAL-SUPPORT] LPS-86068

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-86068

/cc @antonio-ortega

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by julien** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by julien** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63920. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
