### PR TITLE
LPS-102595 Polyfill error at contains function on SVG element on IE11

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hey @julien,

Can you review this pr, please?

Thanks.

/cc @rolandpakai

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
Thanks for the SF @antonio-ortega

**Comment by julien** [comment]
Just started reviewing :)

**Comment by julien** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79137.

**Pull request closed without merging**
