### PR TITLE
LPS-86490 Avoid remaining notification-container element makes non-clickable elements in UI

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi Julien,

Can you review this PR, please?

In [LPS-86490](https://issues.liferay.com/browse/LPS-86490) you can find more information about what is the issue and how to reproduce it.

We have two approaches to solve it:

1. Keep hiding the notification container but make it zero height hence is not blocking any element in the DOM. You can find the reasons for this approach [here](https://issues.liferay.com/browse/LPS-86490?focusedCommentId=1604359&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1604359).
2. Remove the whole notification container from the DOM once the pop-up is closed (because we extended the session or close it clicking on 'X' button). You can find the reasons for this approach [here](https://issues.liferay.com/browse/LPS-84988?focusedCommentId=1606439&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1606439).

If you, as Product Team, decide to pick first option, just get rid of my two commits.

In case you need any help, don't hesitate to ask me.

Thanks,

//cc @NemethNorbert

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by julien** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by julien** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/64448. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
