### PR TITLE
LPS-112943 Deprecate liferay-dd-proxy utility

### PR DESCRIPTION
**Pull request by mateomustapic**
The goal of this task is to deprecate **liferay-dd-proxy** utility.
**liferay-dd-proxy** utility is now marked as deprecated.
This utility has exactly one usage outside of **frontend-js-aui-web**, in **liferay-sortable**, which is already deprecated, so there is no need for updating usages.

### CODE REVIEW

**Comment by mateomustapic** [comment]
ci:test:sf

**Comment by mateomustapic** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Now we just have to wait a couple hours for CI to validate this comment-only change 😂

**Comment by julien** [comment]
ci:forward

**Pull request closed without merging**
