### PR TITLE
LPS-110922 Update liferay-ckeditor to v4.13.1-liferay.4

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:forward

**Comment by julien** [comment]
ci:forward

**Comment by dgarciasarai** [comment]
ci:forward

**Comment by dgarciasarai** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
@julien something was wrong with our network (we'll fix it asap)

I'm merging this one in manually because @jpince told me to.

**Comment by julien** [comment]
@brianchandotcom thanks for the help.

**Pull request closed without merging**
