### PR TITLE
[TECHNICAL-SUPPORT]  LPS-95818

### PR DESCRIPTION
**Pull request by JosemariaMunoz**
https://issues.liferay.com/browse/LPS-95818

### CODE REVIEW

**Comment by JosemariaMunoz** [comment]
ci:test:sf

**Comment by JosemariaMunoz** [comment]
ci:test:relevant

**Comment by JosemariaMunoz** [comment]
ci:test:relevant

**Comment by julien** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73541.

**Pull request closed without merging**
