### PR TITLE
LPS-84119 Update Frontend SF Tool

### PR DESCRIPTION
**Pull request by codyhoag**
Hi Julien,

@jbalsas requested I send this to you to rerun tests and fix whatever is breaking it. This was merged and later reverted in brianchandotcom#63538 due to CI failures.

/cc @hhuijser

### CODE REVIEW

**Comment by julien** [comment]
Hi @codyhoag,

Could you please resolve the conflict in `modules/apps/frontend-js/frontend-js-web/package-lock.json` and resend please?

Thanks

**Comment by julien** [comment]
ci:test

**Comment by julien** [comment]
@codyhoag I ran an `ant all` with your changes and their doesn't seem to be any issue, is there anything in particular you'd like me to check?
Thanks

**Comment by codyhoag** [comment]
@julien I honestly don't know much about the changes. I've generated the `package-lock.json` files two times in the past to propagate the CSF version update, and have had the changes reverted due to CI errors. I was told there was an issue on the frontend side, and to send to you.

That's all I really know :man_shrugging:

**Comment by codyhoag** [comment]
The explanation I received is here: brianchandotcom#63538

**Comment by julien** [comment]
Thanks @codyhoag,

So for the next steps, should I forward this to @brianchandotcom?

**Comment by codyhoag** [comment]
@julien yes please!

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
ci:test

**Comment by julien** [comment]
ci:test-relevant

**Comment by codyhoag** [comment]
@julien I regenerated the files for the latest master. No more conflicts (for now 😅)

**Comment by julien** [comment]
Hey @codyhoag,

Looking at the test errors it seems to be a JS related issue.
I'll have a look and let you know if I manage to fix them.

**Comment by julien** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by julien** [comment]
Hi @codyhoag,

Reseting to commit `9c0e5248c9ced4ad4cd686f574322148dad35cc2` fixed the issue.
I'm still trying to figure out what is happening.

**Comment by julien** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by julien** [comment]
@codyhoag please see https://github.com/julien/liferay-portal/pull/78
I wasn't able to push to your update-frontend-sf-tool branch.
Thanks

**Pull request closed without merging**
