### PR TITLE
[TECHNICAL SUPPORT] LPS-85974 Child pages may disappear if the mouse is not moved quickly enough

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey @julien,
cc @antonio-ortega

[LPS-85974](https://issues.liferay.com/browse/LPS-85974)
I improved on the solution and now the 'showNavigationMenu' event is without delay while still clearing the setTimeOut to avoid closing the dropdown from a delayed 'hideNavigationMenu' event.

Please review it.
Thanks,

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ref https://github.com/antonio-ortega/liferay-portal/pull/61

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by julien** [comment]
Pull request submitted to https://github.com/jbalsas/liferay-portal/pull/1489. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
