### PR TITLE
LPS-110733 Remove TinyMCE WYSIWYG Support

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:stable

**Comment by julien** [comment]
ci:test

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
ci:stop

**Comment by kenjiheigel** [comment]
@julien, your pull request test has been aborted. We are sorry for the inconvenience. QA is in the process of refining the `ci:test:relevant` test suite. Unfortunately this particular pull request test has exceeded the maximum resource limit and will be aborted. Please contact your team's QA representative(s) for next steps. If your team does not have one then please make a post in [#d-quality-assurance](https://liferay.slack.com/archives/CL84ZPHAT)

**Pull request closed without merging**
