### PR TITLE
LPS-78135

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/55557

**Comment by julien** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by julien** [comment]
Pull request sent to https://github.com/brianchandotcom/liferay-portal/pull/55591

**Comment by julien** [comment]
Pull request submitted to https://github.com/boton/liferay-portal/pull/21. [See changes here.](https://github.com/julien/liferay-portal/compare/d5d8536a19~2...d5d8536a19) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
