### PR TITLE
LPS-111247 Replace <liferay-ui:input-editor> with  <liferay-editor:editor> in message-boards-web

### PR DESCRIPTION
**Pull request by julien**
The goal of this change is to replace <liferay-ui:input-editor>
(which was deprecated in 7.1.0) with <liferay-editor:editor>.

Previous Jira tickets https://issues.liferay.com/browse/LPS-110016,
https://issues.liferay.com/browse/LPS-110017 and the corresponding
pull request adolfopa#1332 are
currently in review and change the same files, so the commits made in
that previous pull request have been cherry picked on this branch to
to avoid confusion.

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:stable

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
Hi @John-Co,

I wanted to ask you if you could have a look at the `ci:test:relevant` failures when you have time.

This is a smiliar change than the one I mentioned [here](https://github.com/ambrinchaudhary/liferay-portal/pull/326#issuecomment-607179962), in [`a1109e172469032de6c7f572d49c20166d83c03c`](https://github.com/julien/liferay-portal/pull/262/commits/a1109e172469032de6c7f572d49c20166d83c03c) I've replaced  [`<liferay-ui:input-editor>`](https://github.com/liferay/liferay-portal/blob/ad1be5795224c2d6e22f8939b81427742a55740c/util-taglib/src/com/liferay/taglib/ui/InputEditorTag.java) 
(which was deprecated in 7.1.0) with [`<liferay-editor:editor>`](https://github.com/liferay/liferay-portal/blob/ad1be5795224c2d6e22f8939b81427742a55740c/modules/apps/frontend-editor/frontend-editor-taglib/src/main/java/com/liferay/frontend/editor/taglib/servlet/taglib/EditorTag.java).

Thanks!

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
Hey @John-Co, 
I'm not 100% sure about this, but looking at the poshi results, I see 

```
Type.typeEditor( key_editor = "${editor}", locator1 = "AlloyEditor#EDITOR", value1 = "${content}");
```

So I'm wondering, now that we're using CKEditor, does this need to be changed? 
And if so, could you (when you have time of course) give me a hand with this? 

Thanks!

**Comment by john-co** [comment]
Hi @julien, I believe you're correct. 

The [failing functional tests](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1086871294&testrayRunIdA=1087133476&statusB=2) are all getting stuck on trying to interact with alloyeditor when ckeditor has replaced it.

We should update the poshi test to use ckeditor macros.

@austinchiang, could Lima QA team look into updating the MB tests for this? Let me know if you need help.

I'm not sure about the modules integration error, it looks similar to https://issues.liferay.com/browse/LPS-110700. I'll create an investigation ticket.

**Comment by john-co** [comment]
**Update:**
- The modules-integration error is a known intermittent issue described in https://issues.liferay.com/browse/LPS-105888
- Only test fixes at this point are needed

**Comment by julien** [comment]
@john-co @austinchiang thanks for the details and help

**Comment by julien** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:messageboards

**Comment by julien** [comment]
Re-submitted [here](https://github.com/austinchiang/liferay-portal/pull/753)

**Comment by julien** [comment]
ci:close

**Pull request closed without merging**
