### PR TITLE
LPS-111873 Set to null the itemSelector associated to the instance to avoid reusing it when it is already disposed

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by julien** [comment]
Hey @victorg1991, 
Could you check with QA what's making the test fail? I had a look and it doesn't seem related.

**Comment by victorg1991** [comment]
Let's try one more time

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
