### PR TITLE
[TECHNICAL-SUPPORT] LPS-90239 AlloyEditor source button fails on Firefox and safari for Mac OS

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey @julien ,
cc @antonio-ortega, @jbalsas

[LPS-90239](https://issues.liferay.com/browse/LPS-90239)
I updated the solution, could you please review it?

Thanks,

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf
ci:test:relevant

**Comment by julien** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by julien** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67812. [See changes here.](https://github.com/julien/liferay-portal/compare/699b4d1eb3ff~1...699b4d1eb3ff) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by julien** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67872. [See changes here.](https://github.com/julien/liferay-portal/compare/811b677049b3~1...811b677049b3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
