### PR TITLE
LPS-106842 A container can only being dropped inside the root of Page Editor

### PR DESCRIPTION
**Pull request by diegonvs**

### CODE REVIEW

**Comment by diegonvs** [comment]
From: https://github.com/julien/liferay-portal/pull/196

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
@julien @diegonvs I'll send this pull to Brian (I want to do a massive refactor to PageEditor.js)

**Comment by julien** [comment]
> I want to do a massive refactor to PageEditor.js

:scream: 


Good luck, if you need help don't hesitate.

**Comment by p2kmgcl** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/83214

**Comment by p2kmgcl** [comment]
ci:close

**Pull request closed without merging**
