### PR TITLE
LPS 113973 Enable Accessibility Checker plugin by default

### PR DESCRIPTION
**Pull request by mateomustapic**
The goal of this task is to enable `CKEditor` plugin `Accessibility Checker` by default.

The approach I took to complete this task was to manually download `Accesibility Checker` plugin to `frontend-editor-ckeditor-web`. 
I placed the plugin in _diffs/plugins submodule and added `a11ychecker` to `extraPlugins` and `A11YChecker` button to configuration in `CKEditorConfigContributor` `Java` file.
The issue I had was that `Quail.js` (`JS` testing library) required `jQuery`. 
Global `jQuery` is disabled in portal, so I needed to find a way to make this plugin work wihout enabling global `jQuery`.
I managed to do this by adding jQuery by modifying Accessibility Checker main `plugin.js` file.

The `a11ychecker` is now enabled by default which is visible in the screenshot below

### CODE REVIEW

**Comment by mateomustapic** [comment]
Screenshot at Jun 30 13-07-21

**Comment by mateomustapic** [comment]
ci:test:relevant

**Comment by julien** [comment]
Hey @mateomustapic thanks for sending this.

Just a few details: 

- We're now supposed to send PR's to @liferay-frontend, and assign a reviewer (and/or an assignee): it's explained in a Slack thread [here](https://liferay.slack.com/archives/G3JBR21HA/p1592299966322300) if you want more information.

    Since you were on PTO when that happened, there's no problem, but you'll eventually want to send this PR there (when we've gone through this first "review") because it's always interesting to get feedback from our other colleagues (@jbalsas knows this part very well, @wincent always has interesting feedback and I personally think he can catch stuff we've not been able to see or suggest improvements and @carloslancha is currently working on a new skin for CKEditor which is somewhat related to this feature)

Concerning the change itself:

I've tested this change and the `a11ychecker` plugin is activated by default which is a good thing, but there are things I wanted to talk about:

- What we're doing here is adding the `a11ychecker` plugin directly in the `frontend-editor-ckeditor-web` module, which is one of the options to see it working in `liferay-portal`, but I think the "right" place to do this would be in our [`liferay-ckeditor`](https://github.com/liferay/liferay-ckeditor) repo/package: that way, when we use "our" fork of CKEditor we know this plugin is always going to be enabled by default: that's just what I think, but you might want to get feedback from @jbalsas, @wincent and @carloslancha before taking the decision.

- When I deployed this change and tested in *Blogs* and *Web Content* (my `portal-ext.properties` file is modified to use CKEditor in those places) I didn't see any issue. 
But if you test this with the [latest](https://www.npmjs.com/package/liferay-ckeditor/v/4.13.1-liferay.8) version of `liferay-ckeditor` you'll notice an error coming from the `balloonpanel` plugin related to the `monoo-lexicon` skin's css not being found, as you can see in this screenshot

    balloon-panel-css-error-01

    As we already know the `balloonpanel`  is a dependency of the `a11ychecker` plugin and that's why it's loaded, and this plugin supports skins, so we need to speak with @carloslancha to see how we're going to make that work (there are other plugins that support skins too, not only `balloonpanel`) - From what I'm seeing [here](https://github.com/ckeditor/ckeditor4/tree/4b9240f59b4effd86ce152ee07a5fbcb89e0b8ae/plugins/balloonpanel/skins) we probably need to copy the `monoo-lexicon` skin's files in there and do the same for every plugin that can use skins. This is not directly related to this change, but I still wanted to mention it because we'll have to deal with it at some point. 

- This plugin also requires `jQuery` to work properly, (because under the hood it uses [`Quail`](https://github.com/quailjs/quail) - 
 which needs `jQuery` and which is deprecated, and that's something we might want to talk about too) and the way we're "adding it" is by doing [this](https://github.com/julien/liferay-portal/blob/36668fcc58ca8ad540d89ff03ee51215a009b2bf/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/_diffs/plugins/a11ychecker/plugin.js#L19-L22) which is OK to see it "working" locally, but I think it's definitely not the way we want to do this (once again, that's just my opinion, if I'm wrong I'm sure @jbalsas or @wincent will give us their point of view).
  Have you tried, adding jQuery as a depenency in `liferay-ckeditor` and using that instead, do you think it's possible?
  
- The last thing I wanted to suggest was adding another screenshot of the plugin just to prove (and make it easier for other to see) that we've got it working, something like this maybe 

     a11ychecker-in-portal

**Comment by mateomustapic** [comment]
> Hey @mateomustapic thanks for sending this.
> 
> Just a few details:
> 
> * We're now supposed to send PR's to @liferay-frontend, and assign a reviewer (and/or an assignee): it's explained in a Slack thread [here](https://liferay.slack.com/archives/G3JBR21HA/p1592299966322300) if you want more information.
>   Since you were on PTO when that happened, there's no problem, but you'll eventually want to send this PR there (when we've gone through this first "review") because it's always interesting to get feedback from our other colleagues (@jbalsas knows this part very well, @wincent always has interesting feedback and I personally think he can catch stuff we've not been able to see or suggest improvements and @carloslancha is currently working on a new skin for CKEditor which is somewhat related to this feature)
> 
> Concerning the change itself:
> 
> I've tested this change and the `a11ychecker` plugin is activated by default which is a good thing, but there are things I wanted to talk about:
> 
> * What we're doing here is adding the `a11ychecker` plugin directly in the `frontend-editor-ckeditor-web` module, which is one of the options to see it working in `liferay-portal`, but I think the "right" place to do this would be in our [`liferay-ckeditor`](https://github.com/liferay/liferay-ckeditor) repo/package: that way, when we use "our" fork of CKEditor we know this plugin is always going to be enabled by default: that's just what I think, but you might want to get feedback from @jbalsas, @wincent and @carloslancha before taking the decision.
> * When I deployed this change and tested in _Blogs_ and _Web Content_ (my `portal-ext.properties` file is modified to use CKEditor in those places) I didn't see any issue.
>   But if you test this with the [latest](https://www.npmjs.com/package/liferay-ckeditor/v/4.13.1-liferay.8) version of `liferay-ckeditor` you'll notice an error coming from the `balloonpanel` plugin related to the `monoo-lexicon` skin's css not being found, as you can see in this screenshot
>   balloon-panel-css-error-01
>   As we already know the `balloonpanel`  is a dependency of the `a11ychecker` plugin and that's why it's loaded, and this plugin supports skins, so we need to speak with @carloslancha to see how we're going to make that work (there are other plugins that support skins too, not only `balloonpanel`) - From what I'm seeing [here](https://github.com/ckeditor/ckeditor4/tree/4b9240f59b4effd86ce152ee07a5fbcb89e0b8ae/plugins/balloonpanel/skins) we probably need to copy the `monoo-lexicon` skin's files in there and do the same for every plugin that can use skins. This is not directly related to this change, but I still wanted to mention it because we'll have to deal with it at some point.
> * This plugin also requires `jQuery` to work properly, (because under the hood it uses [`Quail`](https://github.com/quailjs/quail) -
>   which needs `jQuery` and which is deprecated, and that's something we might want to talk about too) and the way we're "adding it" is by doing [this](https://github.com/julien/liferay-portal/blob/36668fcc58ca8ad540d89ff03ee51215a009b2bf/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/_diffs/plugins/a11ychecker/plugin.js#L19-L22) which is OK to see it "working" locally, but I think it's definitely not the way we want to do this (once again, that's just my opinion, if I'm wrong I'm sure @jbalsas or @wincent will give us their point of view).
>   Have you tried, adding jQuery as a depenency in `liferay-ckeditor` and using that instead, do you think it's possible?
> * The last thing I wanted to suggest was adding another screenshot of the plugin just to prove (and make it easier for other to see) that we've got it working, something like this maybe
>   a11ychecker-in-portal

Hey @julien ,
Thank you for this comment.
Regarding first point, yes I was on PTO during this decision and I was aware of @liferay-frontend, but I thought PR’s should be sent there after initial review. However, sorry, this is my mistake and I will send future PR’s there. 

About the changes;
- Regarding jQuery
As you know `Quail.js` depends on jQuery to work. I have tried several approaches to make jQuery work in this plugin, including adding of jQuery as a dependency, but I would get the same error `Uncaught Error: Missing jQuery. Accessibility Checker's default engine, Quail.js requires jQuery to work correctly.`. The only way to make this work in portal without enabling jQuery globally, was to modify the `plugin.js` main file of Accessibility Checker and adding hosted version of jQuery.

- Regarding `balloonpanel`
I did not have an issue with this, I suppose you did because you tested it with the latest version of `ckeditor` and I was working in `frontend-editor-ckeditor-web` module. 
As far as I remember during our talk few days ago, @carloslancha was working on this issue?

- Regarding adding of `a11ychecker` plugin directly in the `frontend-editor-ckeditor-web`
When I was analyzing this task, I realized that there were 2 ways of adding the plugin to be default in CKEditor. 1st way was this one and 2nd was in `lifera—ckeditor` repo. I assumed the first way was sufficient for `liferay-portal` usage.

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by julien** [comment]
> Regarding first point, yes I was on PTO during this decision and I was aware of @liferay-frontend, but I thought PR’s should be sent there after initial review. However, sorry, this is my mistake and I will send future PR’s there.

Don't worry @mateomustapic it's not a mistake, I just wanted to remind it. 

> As you know Quail.js depends on jQuery to work. I have tried several approaches to make jQuery work in this plugin, including adding of jQuery as a dependency, but I would get the same error Uncaught Error: Missing jQuery. Accessibility Checker's default engine, Quail.js requires jQuery to work correctly.. The only way to make this work in portal without enabling jQuery globally, was to modify the plugin.js main file of Accessibility Checker and adding hosted version of jQuery.

So maybe that's not the only way:

Depending on where we decide to add the `a11ychecker` plugin we might have more options.
For example if we decide to add the `a11ychecker` in `frontend-editor-ckeditor-web` module in `liferay-portal`, we probably could add `jQuery` as a dependency and use some "liferay-npm-bundler magic" to make it work (and if we get lost along the way, I'm sure that @izaera can help us make it work) 

If we decide to add it in `liferay-ckeditor` like I suggested in [this](https://github.com/mateomustapic/liferay-ckeditor/pull/1/commits/08a90dcae9d0664ae882cf60093de2a346896382) commit, we could also probably add `jQuery` as a dependency in `liferay-ckeditor` and make it available (I haven't tried all this I'm just thinking about the different options we could explore)

> Regarding balloonpanel
I did not have an issue with this, I suppose you did because you tested it with the latest version of ckeditor and I was working in frontend-editor-ckeditor-web module.
As far as I remember during our talk few days ago, @carloslancha was working on this issue?

As I said, I did test with the latest version because I know @carloslancha has been making new releases lately and I was just anticipating that we wouldn't run into issues. What I said on Slack is that once we'd run into the problem we'd talk with Carlos abut it, but it seems that now is the right time

> Regarding adding of a11ychecker plugin directly in the frontend-editor-ckeditor-web
When I was analyzing this task, I realized that there were 2 ways of adding the plugin to be default in CKEditor. 1st way was this one and 2nd was in lifera—ckeditor repo. I assumed the first way was sufficient for liferay-portal usage.

The plugins that are in the `frontend-editor-ckeditor-web` editor module are there because there are either ours (e.g. `itemselector`) or plugins that have been modified to work correctly in `liferay-portal`. 
In the case of the `a11ychecker` plugin we don't need to modify anything to make it work (we just need to find out how to make `jQuery` available for that plugin somehow)  so that's why I think it should be in `liferay-ckeditor`

**Comment by carloslancha** [comment]
@mateomustapic could you please update the description with the test plan? You can find some guidelines in https://github.com/liferay/liferay-frontend-guidelines/blob/master/dxp/code_review.md
 
My 2cents about the PR:

> The issue I had was that Quail.js (JS testing library) required jQuery.

But, if `Quail.js` is a testing library I see that as a devDependency for testing purposes so... why do we need to enable jQuery in portal?

> As far as I remember during our talk few days ago, @carloslancha was working on this issue?

I was working on the new skin, not in this issue. As @julien said here we need to add the skin `moono-lexicon` with needed css to the file.

> Regarding adding of a11ychecker plugin directly in the frontend-editor-ckeditor-web

As a first step that's fine, we have some other plugins in portal so we cant drop it there to test if it's working. About plugins I think we have two kinds of them:

- Plugins already provided by ckeditor. We just need to include'em in our `liferay-ckeditor` dist from `ckeditor-dev/plugins` (and we're doing it already)
- Custom plugins / plugins not provided by default ckeditor preset. These ones now are living in portal, but I think it could be a good idea to have them in `liferay-ckeditor` for two reasons:
  - I think having everything in the same place is better to understand how everything works and to follow the same development process
   - Skin compatible plugins. There are plugins, like this one, that are skin compatible. In this case we will need to copy our custom skin inside the plugin itself. If we have the plugin living in portal we will need to do this copy every time the skin changes, but if we have it in `liferay-ckeditor` we can just include it during the build process.

**Comment by jbalsas** [comment]
> [...] but I thought PR’s should be sent there after initial review [...]

Hey @mateomustapic, @julien, it should okay to send PRs to individuals in different stages of development when trying to align and validate some things and you don't require the input of everyone in the team. We only really require sending to the `liferay-frontend` user once you want to go through a full review process before pushing it forward.

> But, if Quail.js is a testing library I see that as a devDependency for testing purposes so... why do we need to enable jQuery in portal?

See the screenshots. `Quail.js` is what powers that A11YChecker plugin that runs on the written content inside the WYSIWYG editor.

> In the case of the a11ychecker plugin we don't need to modify anything to make it work (we just need to find out how to make jQuery available for that plugin somehow) so that's why I think it should be in liferay-ckeditor

> Custom plugins / plugins not provided by default ckeditor preset. These ones now are living in portal, but I think it could be a good idea to have them in liferay-ckeditor for two reasons:

In agreement 👍 

By the transitive property, this means we should be figuring out how to bundle jquery as part of that so we produce a fully working package.

**Comment by carloslancha** [comment]
And since we're introducing a plugin with UI we probably want Lexicon team (@drakonux) to be aware of it in case we need to customize the styles

**Comment by jbalsas** [comment]
> And since we're introducing a plugin with UI we probably want Lexicon team (@drakonux) to be aware of it in case we need to customize the styles

It won't hurt... could you create a LEXI ticket to make this request so we make it official?

**Comment by carloslancha** [comment]
> See the screenshots. Quail.js is what powers that A11YChecker plugin that runs on the written content inside the WYSIWYG editor.

@jbalsas gotcha, I understood that Quail was a testing library (for testing) in this line
> The issue I had was that Quail.js (JS testing library) required jQuery

**Comment by drakonux** [comment]
At least we need a proper a11y icon. About styling pop-overs and it's content, we haven't received a formal request yet.  

@carloslancha please add your requests to the CK Editor Epic please: [LEXI-924](https://issues.liferay.com/browse/LEXI-924)

**Comment by wincent** [comment]
> Hey @mateomustapic, @julien, it should okay to send PRs to individuals in different stages of development when trying to align and validate some things and you don't require the input of everyone in the team. We only really require sending to the `liferay-frontend` user once you want to go through a full review process before pushing it forward.

My personal heuristic on this one is that I may as well send everything to liferay-frontend unless it is suuuuper rough. I can send to my own fork if I want to see `ci:test:sf` or `ci:test:relevant` pass before bothering anybody with it, or if I want to park an unfinished WIP (ie. so that I have something to link to in the daily update); but pretty much everything else I would just send to liferay-frontend and assign to a reviewer. There's no real benefit in "hiding" work away from the central repo unless the work is literally "noise", and most of our work won't be like that.

**Comment by wincent** [comment]
Another reason to favor sending to liferay-frontend; this won't ever happen:

Screenshot 2020-07-01 -132727-hBWu0coI@2x

(At least, it won't happen until the cron job that we have updating the repo every 5 minutes dies 😂)

**Comment by julien** [comment]
@mateomustapic I've actually found a way to include jQuery in the plugin, as you can see [here](https://github.com/mateomustapic/liferay-ckeditor/pull/2). I'm not saying this is how it should be done, but it's just a way of getting it "working" - and I know it's far from being ideal.

If you try to deploy that though, you'll still see the error related to the skin's css file as I commented [here](https://github.com/julien/liferay-portal/pull/288#issuecomment-652300261).

So here's what I think:

We first need to ask @carloslancha to include skins for the following plugins: 

```
./plugins/balloonpanel/skins
./plugins/balloontoolbar/skins
./plugins/emoji/skins
./plugins/autocomplete/skins
```

And concerning the `ay11checker` plugin, I saw that on the plugins [page](https://ckeditor.com/cke4/addon/a11ychecker), it says 

> The default implementation uses Quail as its accessibility tests library, but you can integrate any other similar library to achieve comparable results.

Since [Quail](https://github.com/quailjs/quail) is deprecated and archived, what would you think about exploring the other available options. Maybe some don't depend on `jQuery`.

Tell me what you think when you can

**Comment by mateomustapic** [comment]
> @mateomustapic I've actually found a way to include jQuery in the plugin, as you can see [here](https://github.com/mateomustapic/liferay-ckeditor/pull/2). I'm not saying this is how it should be done, but it's just a way of getting it "working" - and I know it's far from being ideal.
> 
> If you try to deploy that though, you'll still see the error related to the skin's css file as I commented [here](https://github.com/julien/liferay-portal/pull/288#issuecomment-652300261).
> 
> So here's what I think:
> 
> We first need to ask* @carloslancha to include skins for the following plugins:
> 
> ```
> ./ckeditor/plugins/balloonpanel/skins
> ./ckeditor/plugins/balloontoolbar/skins
> ./ckeditor/plugins/emoji/skins
> ./ckeditor/plugins/autocomplete/skins
> ```
> 
> (* We can also copy the files for the time being and deal with that later)
> 
> And concerning the `ay11checker` plugin, I saw that on the plugins [page](https://ckeditor.com/cke4/addon/a11ychecker), it says
> 
> > The default implementation uses Quail as its accessibility tests library, but you can integrate any other similar library to achieve comparable results.
> 
> Since [Quail](https://github.com/quailjs/quail) is deprecated and archived, what would you think about exploring the other available options. Maybe some don't depend on `jQuery`.
> 
> Tell me what you think when you can

Thanks for this. 
I can focus on finding a way to make this plugin work without Quail which would eliminate jQuery from the solution and make this job a lot easier.

**Comment by julien** [comment]
@mateomustapic after reading the [documentation](https://ckeditor.com/docs/ckeditor4/latest/features/accessibility_checker.html) for the `a11ychecker` plugin, I don't think it's going to be that easy, because the only information I can see is 

> The default checking engine is Quail, but you are free to integrate any other library you want — it can be written in JavaScript, PHP, Java, .NET or any other language of your choice.

And on [Quail](https://github.com/quailjs/quail#deprecation)'s side, this is what I read 

> If you are looking for one, we recommend aXe: the Accessibility Engine by Deque Labs.

The for me the next questions we need to answer would be:

How easy is it to configure the `ay11checker` plugin to use aXe?
Does aXe also depend on jQuery?

**Comment by jbalsas** [comment]
> I can focus on finding a way to make this plugin work without Quail which would eliminate jQuery from the solution and make this job a lot easier.

I doubt this would actually make your job a lot easier, since you'll need to plug `axe` or any other library to power the CKEditor plugin.

I'd suggest you first figure out how to integrate jQuery (could be as simple as copy-pasting  it) and get this done. Then, we can analyze future improvements. But if you all should try to close things before opening new avenues because you don't know what's waiting for you down the road.

**Comment by mateomustapic** [comment]
> > I can focus on finding a way to make this plugin work without Quail which would eliminate jQuery from the solution and make this job a lot easier.
> 
> I doubt this would actually make your job a lot easier, since you'll need to plug `axe` or any other library to power the CKEditor plugin.
> 
> I'd suggest you first figure out how to integrate jQuery (could be as simple as copy-pasting it) and get this done. Then, we can analyze future improvements. But if you all should try to close things before opening new avenues because you don't know what's waiting for you down the road.



> @mateomustapic after reading the [documentation](https://ckeditor.com/docs/ckeditor4/latest/features/accessibility_checker.html) for the `a11ychecker` plugin, I don't think it's going to be that easy, because the only information I can see is
> 
> > The default checking engine is Quail, but you are free to integrate any other library you want — it can be written in JavaScript, PHP, Java, .NET or any other language of your choice.
> 
> And on [Quail](https://github.com/quailjs/quail#deprecation)'s side, this is what I read
> 
> > If you are looking for one, we recommend aXe: the Accessibility Engine by Deque Labs.
> 
> The for me the next questions we need to answer would be:
> 
> How easy is it to configure the `ay11checker` plugin to use aXe?
> Does aXe also depend on jQuery?

I found this discussion https://www.drupal.org/project/drupal/issues/2731373 where this plugin and its dependency on deprecated Quail is discussed. 
Due to this reason it is not advised to use Accessibility Checker plugin because it would represent a security issue.

**Comment by mateomustapic** [comment]
> > I can focus on finding a way to make this plugin work without Quail which would eliminate jQuery from the solution and make this job a lot easier.
> 
> I doubt this would actually make your job a lot easier, since you'll need to plug `axe` or any other library to power the CKEditor plugin.
> 
> I'd suggest you first figure out how to integrate jQuery (could be as simple as copy-pasting it) and get this done. Then, we can analyze future improvements. But if you all should try to close things before opening new avenues because you don't know what's waiting for you down the road.

Ok, based on what Julien sent me [https://github.com/mateomustapic/liferay-ckeditor/pull/2] - I'm going to copy jQuery inside the a11ychecker plugin and see if we can improve that later on.

**Comment by wincent** [comment]
> Ok, based on what Julien sent me https://github.com/[mateomustapic/liferay-ckeditor/pull/2 - I'm going to copy jQuery inside the a11ychecker plugin and see if we can improve that later on.

Please take into consideration my comments on that PR as you develop your solution. Especially, [make sure you use `devDependencies`](https://github.com/mateomustapic/liferay-ckeditor/pull/2#discussion_r448319092)), and I'd [like to know whether](https://github.com/mateomustapic/liferay-ckeditor/pull/2#issuecomment-652381196):

> So is this going to end up defining a jQuery global? Is there a way to inject this into the plugin without polluting the global namespace?

Looking at a built copy I do see a file called `adapters/jquery.js`, which has the following unfortunate code in it:

```
(function(a){if("undefined"==typeof a)throw Error("jQuery should be loaded before CKEditor jQuery adapter.");/* ... a bunch of other shit ... */})(window.jQuery);
```

which sure makes it look like it might want `window.jQuery` to be defined 😢  — still, worth looking into seeing if that can be avoided.

**Comment by jbalsas** [comment]
I'd expect https://zeptojs.com/ could be a viable alternative... 🤔

**Comment by mateomustapic** [comment]
> > Ok, based on what Julien sent me [https://github.com/[mateomustapic/liferay-ckeditor/pull/2](https://github.com/%5Bmateomustapic/liferay-ckeditor/pull/2) - I'm going to copy jQuery inside the a11ychecker plugin and see if we can improve that later on.
> 
> Please take into consideration my comments on that PR as you develop your solution. Especially, [make sure you use `devDependencies`](https://github.com/mateomustapic/liferay-ckeditor/pull/2#discussion_r448319092)), and I'd [like to know whether](https://github.com/mateomustapic/liferay-ckeditor/pull/2#issuecomment-652381196):
> 
> > So is this going to end up defining a jQuery global? Is there a way to inject this into the plugin without polluting the global namespace?
> 
> Looking at a built copy I do see a file called `adapters/jquery.js`, which has the following unfortunate code in it:
> 
> ```
> (function(a){if("undefined"==typeof a)throw Error("jQuery should be loaded before CKEditor jQuery adapter.");/* ... a bunch of other shit ... */})(window.jQuery);
> ```
> 
> which sure makes it look like it might want `window.jQuery` to be defined 😢 — still, worth looking into seeing if that can be avoided.

Of course, I followed all your comments in this PR :)

**Comment by julien** [comment]
> I'd expect https://zeptojs.com/ could be a viable alternative... thinking

> At least worth testing...

That's a good idea (+ fixing what @wincent suggested)

**Comment by carloslancha** [comment]
> We first need to ask* @carloslancha to include skins for the following plugins:

./ckeditor/plugins/balloonpanel/skins
./ckeditor/plugins/balloontoolbar/skins
./ckeditor/plugins/emoji/skins
./ckeditor/plugins/autocomplete/skins

I'll send a pr automating the addition of the skin to specified plugins, could you guys @julien or @mateomustapic create an IFI for this task in CKEditor Epic so we have the full context?

Thx!

**Comment by julien** [comment]
Hey @carloslancha sure we can create an IFI - but I actually think it's part of the original [task](https://issues.liferay.com/browse/LPS-116201) to create the skin.

I'll take care of this.

**Comment by julien** [comment]
@mateomustapic since we needed to do changes in `liferay-ckeditor`, I submitted [#86](https://github.com/liferay/liferay-ckeditor/pull/86) and once that's reviewed and merged, I think the only thing left to do would be to enable the `a11ychecker` plugin (and add the `A11Ychecker` button to the editor's toolbar). - So I'm going to close this pull request for now.

**Pull request closed without merging**
