### PR TITLE
LPS-109997 Replace alloyeditor title with aui:input

### PR DESCRIPTION
**Pull request by mateomustapic**

### CODE REVIEW

**Comment by julien** [comment]
Just started reviewing

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
Hi @mateomustapic 

It's a good start, but we're still missing a few things to make it look identical to what we had before.

1. I had to test this several times to make sure it was not something wrong on my end, but when I deploy these change, the `<select>` elements look wrong, as you can see in this screenshot

01-select

2. The cursor's position, should be at the beginning of the title, the same position as the border 

3. The border shouldn't be visible when typing, it should be applied to the `input`'s placeholder

4. The text color is wrong when typing, it should be much darker

5. The length (or size/width) of the input is too small

6. We need to fix the source formatter issues as well

7. One thing I'm not sure about, is about [creating the new variable](https://github.com/julien/liferay-portal/blob/2b31d70a0d2972b5650a60b79a903150cfda0cb2/modules/apps/announcements/announcements-web/src/main/resources/META-INF/resources/announcements/css/main.scss#L1) in the .scss file but we can ask the rest of the team if this is OK. (@marcoscv-work or @eduardoallegrini should know the anwser)

If you need more details or help, as usual feel free to ping me anytime on Slack

Thanks!

**Comment by mateomustapic** [comment]
> Hi @mateomustapic
> 
> It's a good start, but we're still missing a few things to make it look identical to what we had before.
> 
> 1. I had to test this several times to make sure it was not something wrong on my end, but when I deploy these change, the `<select>` elements look wrong, as you can see in this screenshot
> 
> 01-select
> 
> 1. The cursor's position, should be at the beginning of the title, the same position as the border
> 2. The border shouldn't be visible when typing, it should be applied to the `input`'s placeholder
> 3. The text color is wrong when typing, it should be much darker
> 4. The length (or size/width) of the input is too small
> 5. We need to fix the source formatter issues as well
> 6. One thing I'm not sure about, is about [creating the new variable](https://github.com/julien/liferay-portal/blob/2b31d70a0d2972b5650a60b79a903150cfda0cb2/modules/apps/announcements/announcements-web/src/main/resources/META-INF/resources/announcements/css/main.scss#L1) in the .scss file but we can ask the rest of the team if this is OK. (@marcoscv-work or @eduardoallegrini should know the anwser)
> 
> If you need more details or help, as usual feel free to ping me anytime on Slack
> 
> Thanks!

Made required changes in new PR https://github.com/julien/liferay-portal/pull/234

Closing this one.

**Pull request closed without merging**
