### PR TITLE
LPS-110830 Use default value to avoid error accessing properties

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by julien** [comment]
ci:forward

**Comment by wincent** [comment]
@victorg1991: one thing about [the fix](https://github.com/julien/liferay-portal/pull/244/commits/4bf45c969c673fe6fec87728cec016225fa1e179) — this looks like a mitigation but it would be nice to identify the root cause. Why is there ever an `id` that refers to a non-existent node? Is it because we're feeding bad data to the component?

**Comment by victorg1991** [comment]
Hey @wincent It happens because we are adding new nodes to the tree

**Comment by victorg1991** [comment]
ci:forward

**Comment by wincent** [comment]
> Hey @wincent It happens because we are adding new nodes to the tree

So how is that update happening?

**Comment by victorg1991** [comment]
@wincent the nodes prop that the component receives is changing between renders that is why the update_nodes is being called, is that what you mean? 🤔

**Comment by wincent** [comment]
> @wincent the nodes prop that the component receives is changing between renders that is why the update_nodes is being called, is that what you mean? 🤔

Yes. Ok, thanks for clarifying that. I think the change is safe, but I wanted to be sure because we access `nodeMap` in a bunch of places but we'll only ever call `init` once (to create it in the first place), and I think the `UPDATE_NODES` action is the only place we'll run into the case you're fixing here.

**Comment by julien** [comment]
ci:stop

**Pull request closed without merging**
