### PR TITLE
LPS-95425 Replaces polyfills with core-js-bundle@3 for better consistency and correctness in IE11

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by wincent** [comment]
So much simpler!

We should probably also evaluate whether we need to make changes with what we're doing with `@babel/preset-env` [here](https://github.com/liferay/liferay-npm-tools/blob/4dbf731fb9cb9dc1fc15d93ca8d83fcb9d92ce73/packages/liferay-npm-scripts/src/config/babel.json#L2). There's a chance that might be adding overlapping polyfills because it [will target](https://github.com/browserslist/browserslist#full-list) `> 0.5%, last 2 versions, Firefox ESR, not dead`; what we want is to transpile for IE 11 etc, but only add polyfills that are needed by non-IE browsers (because we ship the IE polyfills separately).

**Comment by jbalsas** [comment]
exactly! I’m looking into it next!

**Comment by julien** [comment]
Just started reviewing.

**Comment by jbalsas** [comment]
So, after a quick look into it:
- We're currently using `core-js@2` as per default in `@babel/preset-env`
- The current behaviour is that no polyfills are added to the code
- If we move to `corejs: 3` and `useBuiltIns: "usage"` then a bunch of "unnecessary" polyfills are indeed required

```javascript
  require("frontend-js-metal-web$core-js/modules/es.symbol");
  require("frontend-js-metal-web$core-js/modules/es.symbol.description");
  require("frontend-js-metal-web$core-js/modules/es.symbol.iterator");
  require("frontend-js-metal-web$core-js/modules/es.array.concat");
  require("frontend-js-metal-web$core-js/modules/es.array.for-each");
  require("frontend-js-metal-web$core-js/modules/es.array.iterator");
  require("frontend-js-metal-web$core-js/modules/es.array.slice");
  require("frontend-js-metal-web$core-js/modules/es.array.some");
  require("frontend-js-metal-web$core-js/modules/es.date.to-string");
  require("frontend-js-metal-web$core-js/modules/es.object.assign");
  require("frontend-js-metal-web$core-js/modules/es.object.create");
  require("frontend-js-metal-web$core-js/modules/es.object.define-property");
  require("frontend-js-metal-web$core-js/modules/es.object.get-own-property-descriptor");
  require("frontend-js-metal-web$core-js/modules/es.object.get-prototype-of");
  require("frontend-js-metal-web$core-js/modules/es.object.keys");
  require("frontend-js-metal-web$core-js/modules/es.object.set-prototype-of");
  require("frontend-js-metal-web$core-js/modules/es.object.to-string");
  require("frontend-js-metal-web$core-js/modules/es.promise");
  require("frontend-js-metal-web$core-js/modules/es.reflect.get");
  require("frontend-js-metal-web$core-js/modules/es.regexp.to-string");
  require("frontend-js-metal-web$core-js/modules/es.string.iterator");
  require("frontend-js-metal-web$core-js/modules/web.dom-collections.iterator");
  require("frontend-js-metal-web$core-js/modules/web.timers");
  require("frontend-js-metal-web$core-js/modules/web.url");
```

- Moving to `corejs: 3` and `useBuiltIns: false` seems to produce the same output as with `corejs@2`.

I don't think there's a way to configure this to transpile for all browsers but add polyfills only for IE11 so it seems that either `useBuiltIns: false` with `corejs: 3` or just keeping the current defaults are our better approach here.

If the previous assessment is correct, I'd say staying put would be my preferred approach.

@julien, @wincent, thoughts?

**Comment by wincent** [comment]
> If the previous assessment is correct, I'd say staying put would be my preferred approach.

Sounds like a plan. Ship it and watch for smoke.

**Comment by julien** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76899.

**Pull request closed without merging**
