### PR TITLE
LPS-133161

### PR DESCRIPTION
**Pull request by yxingwu**
Hello @julien ，
Hope you're the right person to review.

### CODE REVIEW

**Comment by yxingwu** [comment]
ci:test:sf

**Comment by yxingwu** [comment]
ci:test:relevant

**Comment by julien** [comment]
Hi @yxingwu,

Thanks for sending this. Unfortunately, this is not an official "team" repository, just a clone.
Please send your pull request to [@liferay-frontend/liferay-portal](https://github.com/liferay-frontend/liferay-portal). 

If you need any help, please let know.

**Comment by julien** [comment]
ci:close

**Comment by julien** [comment]
ci:stop

**Pull request closed without merging**
