### PR TITLE
LPS-103180 Use Metal `disposed` lifecycle instead of calling Component's `disposeInternal`

### PR DESCRIPTION
**Pull request by diegonvs**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark:

**Comment by john-co** [comment]
**[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=870545477&testrayRunIdA=871144962&statusB=2)**

Test failures were flukes or also observed in latest PRs.

**Comment by julien** [comment]
Just started reviewing :)

**Comment by julien** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80919.

**Comment by julien** [comment]
Pull request submitted to https://github.com/jbalsas/liferay-portal/pull/2033.

**Pull request closed without merging**
