### PR TITLE
LPS-74564 Remove old markup from taglibs: FieldsetTag

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
Hi @alee8888,

Could you help me figure out if the failures are related to my changes?

Thanks!

**Comment by julien** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
@julien 
If the ci retest comes back with the SitelocalizationUsecase#SiteTemplateLocalization failure, then that failure was likely caused by your pull because it's not failing in other places.

With regards to the actual failure, you can run the test by running (with portal already running):
"ant -f build-test-tomcat.xml run-selenium-test -Dtest.class=SitelocalizationUsecase#SiteTemplateLocalization"

The failure is that it's looking at this locator "//div[contains(@id,'siteTemplateContent')]//div//div" and looking for the text "This site was cloned from site template Site Template Name" but cannot see it there.

cc @anthony-chu - can you take a look when you have a chance?

**Comment by julien** [comment]
@brianchiu Thanks for the information.
 
I'll run the tests locally and see if I can get understand what's failing.

**Comment by julien** [comment]
@brianchiu, @anthony-chu, after running the tests locally with:

```
ant -f build-test-tomcat.xml run-selenium-test -Dtest.class=SitelocalizationUsecase#SiteTemplateLocalization
```

The following error is thrown

```
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
ver@googlecode.com in app-profile

# more stack traces

org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(/Applications/Firefox.app/Contents/MacOS/firefox-bin) on port 7055; process output follows: 
ver@googlecode.com in app-profile
```

Firefox (56.0) is installed on my machine. Do I need to setup anything else?

Thanks again for your help

**Comment by julien** [comment]
Just wanted to confirm that this also happens by cloning the [portal](https://github.com/liferay/liferay-portal) repository directly, so  either I'm not setting up everything correctly or the tests are simply failing.

**Comment by jpince** [comment]
@julien can you try undeploying the chat portlet? (easiest way is to start over and delete that portlet before startup) `Other element would receive the click: <div class="chat-bar"></div>` It is blacklisted (blocked from deploying) in CI because it interferes with our tests (as you discovered)

POSHI is certified on Firefox 45esr and prior, it has not been updated to work with the latest version of Firefox, sorry for that confusion.

If it helps, you can send a pull directly to @alee8888 and CI will automatically generate a tomcat bundle that you can use to test once all tests are complete (link will appear at the bottom of the test result comment, you may need to VPN in to access with your Liferay login).

**Comment by brianchiu** [comment]
@julien 
Ahhh sorry. As Jason said, you would have to use Firefox 45 (https://ftp.mozilla.org/pub/firefox/releases/45.0esr/). This is because we're using Selenium 2.53.0, which supports Firefox 45 and earlier.

Also, make sure that your firefox bin directory is in your path. Then it should work.

**Comment by julien** [comment]
@jpince @brianchiu Thanks for the information, I've been able to run the tests (successfully) locally by using Firefox 45 and disabling the chat portlet.

Based on your feedback, I will send pull requests to  @alee8888 

Thanks again for the help.

**Pull request closed without merging**
